name: build
on:
  push:
    branches:
      - main
jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, ubuntu-20.04]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        if: matrix.os == 'ubuntu-20.04'
      - uses: Swatinem/rust-cache@v2
      - run: cargo build --release --target x86_64-unknown-linux-gnu
      - name: echo sha256
        run: sha256sum ./target/x86_64-unknown-linux-gnu/release/nodecook-agent
      - name: Minio Deploy
        uses: yakubique/minio-upload@v1.1.3
        with:
          endpoint: ${{ secrets.MINIO_ENDPOINT }}
          access_key: ${{ secrets.MINIO_ACCESS_KEY }}
          secret_key: ${{ secrets.MINIO_SECRET_KEY }}
          bucket: nodecook
          source: ./target/x86_64-unknown-linux-gnu/release/nodecook-agent
          target: ${{ matrix.os == 'ubuntu-latest' && '/agent' || '/agent-ubuntu-20.04'}}
